//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_EYEAssets/_Input/UIChargeBarInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UIChargeBarInputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UIChargeBarInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIChargeBarInputs"",
    ""maps"": [
        {
            ""name"": ""UIChargeBar"",
            ""id"": ""eaa03785-926d-4371-a90a-5300792858a6"",
            ""actions"": [
                {
                    ""name"": ""Charge"",
                    ""type"": ""Button"",
                    ""id"": ""0aff085d-f5df-4e78-842a-2afb0a23c947"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b14a4fb3-514e-4497-b7f5-0cc30c802f3e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Charge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // UIChargeBar
        m_UIChargeBar = asset.FindActionMap("UIChargeBar", throwIfNotFound: true);
        m_UIChargeBar_Charge = m_UIChargeBar.FindAction("Charge", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // UIChargeBar
    private readonly InputActionMap m_UIChargeBar;
    private IUIChargeBarActions m_UIChargeBarActionsCallbackInterface;
    private readonly InputAction m_UIChargeBar_Charge;
    public struct UIChargeBarActions
    {
        private @UIChargeBarInputs m_Wrapper;
        public UIChargeBarActions(@UIChargeBarInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Charge => m_Wrapper.m_UIChargeBar_Charge;
        public InputActionMap Get() { return m_Wrapper.m_UIChargeBar; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIChargeBarActions set) { return set.Get(); }
        public void SetCallbacks(IUIChargeBarActions instance)
        {
            if (m_Wrapper.m_UIChargeBarActionsCallbackInterface != null)
            {
                @Charge.started -= m_Wrapper.m_UIChargeBarActionsCallbackInterface.OnCharge;
                @Charge.performed -= m_Wrapper.m_UIChargeBarActionsCallbackInterface.OnCharge;
                @Charge.canceled -= m_Wrapper.m_UIChargeBarActionsCallbackInterface.OnCharge;
            }
            m_Wrapper.m_UIChargeBarActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Charge.started += instance.OnCharge;
                @Charge.performed += instance.OnCharge;
                @Charge.canceled += instance.OnCharge;
            }
        }
    }
    public UIChargeBarActions @UIChargeBar => new UIChargeBarActions(this);
    public interface IUIChargeBarActions
    {
        void OnCharge(InputAction.CallbackContext context);
    }
}
